---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    {{- define "backend.paths" }}
    http:
      paths:
      {{- with $.Values.api.management_endpoint }}
      - path: /api/v1{{.}}
        backend:
          serviceName: none
          servicePort: 80
      {{- end }}
      - path: /api
        backend:
          serviceName: backend
          servicePort: 80
      - path: /auth
        backend:
          serviceName: backend
          servicePort: 80
    {{- end }}
  # Allows access via
  # http://<namespace>.<nginx_svc_load_balancer_ip>.xip.io.
  # See https://github.com/kubernetes/kubernetes/issues/41881
  - host: {{ .Values.namespace }}
{{- include "backend.paths" . }}
  - host: {{ .Values.api.domain }}
{{- include "backend.paths" . }}
  {{- range .Values.api.extraDomains }}
  - host: {{ . }}
{{- include "backend.paths" . }}
  {{- end }}

  {{- if eq .Values.tls true }}
  tls:
    - secretName: {{ .Values.api.domain | replace "." "-" }}-tls
      hosts:
        - {{ .Values.api.domain }}
        {{- range .Values.api.extraDomains }}
        - {{ . }}
        {{- end }}
  {{- end }}
